=== bouzeko/e-shop/Schema.xsd
<?xml version 1.0 encoding="UTF-8"?>
<!--Odkaz na github: https://github.com/bouzeko/e-shop/-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="e-shop">
    <xs:annotation>
      <xs:documentation>E-shop s hudebními nástrojiNastavení zobrazení</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nastaveni-zobrazeni">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="max-pocet-zaznamu"/>
              <xs:element type="jazyk-set" name="jazyk" default="CZ"/>
              <xs:element type="mena-set" name="mena"/>
              <xs:element type="charset-set" name="charset" default="utf-8"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="nastaveni-pristupu">
          <xs:annotation>
            <xs:documentation>Nastavení přístupu</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="role" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="ano-ne" name="uprava-ceny"/>
                    <xs:element type="ano-ne" name="uprava-stavu"/>
                    <xs:element type="ano-ne" name="uprava-udaju"/>
                  </xs:sequence>
                  <xs:attribute type="role-set" name="nazev" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="pristup-podle-stavu">
          <xs:annotation>
            <xs:documentation>Nastavení přístupu různými rolemi podle stavu zboží</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="stav" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="ano-ne" name="admin"/>
                    <xs:element type="ano-ne" name="vedouci"/>
                    <xs:element type="ano-ne" name="zamestnanec"/>
                    <xs:element type="ano-ne" name="zakaznik"/>
                  </xs:sequence>
                  <xs:attribute type="stav-zbozi" name="jmeno" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="databaze-nastroju">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="kategorie" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Kategorie 1 - ElektrickéKategorie 2 - AkustickéKategorie 3 - BaskytaryKategorie 4 - Ukulele</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="nazev-kategorie" name="nazev-kat"/>
                    <xs:element name="nastroj" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="znacka"/>
                          <xs:element type="xs:string" name="druh"/>
                          <xs:element type="xs:string" name="barva"/>
                          <xs:element type="kod" name="kod-zbozi"/>
                          <xs:element type="xs:short" name="rok-vyroby"/>
                          <xs:element type="xs:short" name="cena"/>
                          <xs:element type="stav-zbozi" name="stav" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute type="id-nastroje" name="id" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="cislo" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!--Nastavení jazyka-->
  <xs:simpleType name="jazyk-set">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CZ"/>
      <xs:enumeration value="EN"/>
      <xs:enumeration value="DE"/>
      <xs:enumeration value="FR"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Nastavení měny-->
  <xs:simpleType name="mena-set">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CZK"/>
      <xs:enumeration value="EUR"/>
      <xs:enumeration value="USD"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Nastavení charsetu-->
  <xs:simpleType name="charset-set">
    <xs:restriction base="xs:string">
      <xs:enumeration value="utf-8"/>
      <xs:enumeration value="windows-1258"/>
      <xs:enumeration value="utf-7"/>
      <xs:enumeration value="iso-8859"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Nastavení role-->
  <xs:simpleType name="role-set">
    <xs:restriction base="xs:string">
      <xs:enumeration value="admin"/>
      <xs:enumeration value="vedouci"/>
      <xs:enumeration value="zamestnanec"/>
      <xs:enumeration value="zakaznik"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Nastavení ano-ne-->
  <xs:simpleType name="ano-ne">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ano"/>
      <xs:enumeration value="ne"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Názvy kategorie-->
  <xs:simpleType name="nazev-kategorie">
    <xs:restriction base="xs:string">
      <xs:enumeration value="elektrické"/>
      <xs:enumeration value="akustické"/>
      <xs:enumeration value="baskytary"/>
      <xs:enumeration value="ukulele"/>
    </xs:restriction>
  </xs:simpleType>
  
   <!--Kód zboží-->
  <xs:simpleType name="kod">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Stav zboží-->
  <xs:simpleType name="stav-zbozi">
    <xs:restriction base="xs:string">
      <xs:enumeration value="skladem"/>
      <xs:enumeration value="na-prodejne"/>
      <xs:enumeration value="objednane"/>
      <xs:enumeration value="nedostupne"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--ID nástroje-->
  <xs:simpleType name="id-nastroje">
    <xs:restriction base="xs:string">
      <xs:pattern value="([A-Z][0-9])+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== bouzeko/e-shop/Data.xml
<?xml version="1.0" encoding="utf-8"?>
<!--E-shop s hudebními nástroji-->
<!--Odkaz na github: https://github.com/bouzeko/e-shop/-->
<!--Nastavení zobrazení-->
<e-shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:noNamespaceSchemaLocation="Schema.xsd">
<nastaveni-zobrazeni>
  <max-pocet-zaznamu>20</max-pocet-zaznamu>
  <jazyk>CZ</jazyk>
  <mena>CZK</mena>
  <charset>utf-8</charset>
</nastaveni-zobrazeni>

<!--Nastavení přístupu-->
<nastaveni-pristupu>
  <role nazev="admin">
    <uprava-ceny>ano</uprava-ceny>
    <uprava-stavu>ano</uprava-stavu>
    <uprava-udaju>ano</uprava-udaju>
  </role>
  <role nazev="vedouci">
    <uprava-ceny>ne</uprava-ceny>
    <uprava-stavu>ano</uprava-stavu>
    <uprava-udaju>ano</uprava-udaju>
  </role>
  <role nazev="zamestnanec">
    <uprava-ceny>ne</uprava-ceny>
    <uprava-stavu>ano</uprava-stavu>
    <uprava-udaju>ne</uprava-udaju>
  </role>
  <role nazev="zakaznik">
    <uprava-ceny>ne</uprava-ceny>
    <uprava-stavu>ne</uprava-stavu>
    <uprava-udaju>ne</uprava-udaju>
  </role>
</nastaveni-pristupu>

<!--Nastavení přístupu různými rolemi podle stavu zboží-->
<pristup-podle-stavu>
  <stav jmeno="skladem">
    <admin>ano</admin>
    <vedouci>ano</vedouci>
    <zamestnanec>ano</zamestnanec>
    <zakaznik>ano</zakaznik>
  </stav>
  <stav jmeno="na-prodejne">
    <admin>ano</admin>
    <vedouci>ano</vedouci>
    <zamestnanec>ano</zamestnanec>
    <zakaznik>ano</zakaznik>
  </stav>
  <stav jmeno="objednane">
    <admin>ano</admin>
    <vedouci>ano</vedouci>
    <zamestnanec>ano</zamestnanec>
    <zakaznik>ne</zakaznik>
  </stav>
  <stav jmeno="nedostupne">
    <admin>ano</admin>
    <vedouci>ano</vedouci>
    <zamestnanec>ne</zamestnanec>
    <zakaznik>ne</zakaznik>
  </stav>
</pristup-podle-stavu>

<databaze-nastroju>
<!--Kategorie 1 - Elektrické-->
  <kategorie cislo="1">
    <nazev-kat>elektrické</nazev-kat>
      <nastroj id="E1">
        <znacka>Fender</znacka>
        <druh>Stratocaster</druh>
        <barva>bílá</barva>
        <kod-zbozi>NHF2932</kod-zbozi>
        <rok-vyroby>2003</rok-vyroby>
        <cena>13290</cena>
        <stav>skladem</stav>
      </nastroj>    
      <nastroj id="E2">
        <znacka>Gibson</znacka>
        <druh>Les Paul</druh>
        <barva>černá</barva>
        <kod-zbozi>KLP1273</kod-zbozi>
        <rok-vyroby>2012</rok-vyroby>
        <cena>16900</cena>
        <stav>skladem</stav>
      </nastroj>
      <nastroj id="E3">
        <znacka>Epiphone</znacka>
        <druh>Archtop</druh>
        <barva>žlutá</barva>
        <kod-zbozi>EAT0235</kod-zbozi>
        <rok-vyroby>2011</rok-vyroby>
        <cena>9900</cena>
        <stav>na-prodejne</stav>
      </nastroj>
      <nastroj id="E4">
        <znacka>Gibson</znacka>
        <druh>SG</druh>
        <barva>přírodní</barva>
        <kod-zbozi>ACG1204</kod-zbozi>
        <rok-vyroby>2015</rok-vyroby>
        <cena>15150</cena>
        <stav>nedostupne</stav>
      </nastroj>
  </kategorie>

<!--Kategorie 2 - Akustické-->
  <kategorie cislo="2">
    <nazev-kat>akustické</nazev-kat>
      <nastroj id="A1">
        <znacka>Cort</znacka>
        <druh>Dreadnought</druh>
        <barva>prirodni</barva>
        <kod-zbozi>ZKC7658</kod-zbozi>
        <rok-vyroby>2010</rok-vyroby>
        <cena>5600</cena>
        <stav>objednane</stav>
      </nastroj>
      <nastroj id="A2">
        <znacka>Ibanez</znacka>
        <druh>Jumbo</druh>
        <barva>červená</barva>
        <kod-zbozi>IJC4581</kod-zbozi>
        <rok-vyroby>2017</rok-vyroby>
        <cena>8900</cena>
        <stav>objednane</stav>
      </nastroj>
      <nastroj id="A3">
        <znacka>Gibson</znacka>
        <druh>Dreadnought</druh>
        <barva>černá</barva>
        <kod-zbozi>GDC3641</kod-zbozi>
        <rok-vyroby>2009</rok-vyroby>
        <cena>10120</cena>
        <stav>skladem</stav>
      </nastroj>
      <nastroj id="A4">
        <znacka>Stagg</znacka>
        <druh>španělská</druh>
        <barva>modrá</barva>
        <kod-zbozi>SSM0708</kod-zbozi>
        <rok-vyroby>2005</rok-vyroby>
        <cena>2800</cena>
        <stav>na-prodejne</stav>
      </nastroj>
   </kategorie>
<!--Kategorie 3 - Baskytary-->
  <kategorie cislo="3">
    <nazev-kat>baskytary</nazev-kat>
      <nastroj id="B1">
        <znacka>Squier</znacka>
        <druh>Jazz Bass</druh>
        <barva>oranžová</barva>
        <kod-zbozi>SJB2143</kod-zbozi>
        <rok-vyroby>2016</rok-vyroby>
        <cena>4300</cena>
        <stav>nedostupne</stav>
      </nastroj>
      <nastroj id="B2">
        <znacka>Fender</znacka>
        <druh>Precison Bass</druh>
        <barva>přírodní</barva>
        <kod-zbozi>FPB7410</kod-zbozi>
        <rok-vyroby>2016</rok-vyroby>
        <cena>9600</cena>
        <stav>na-prodejne</stav>
      </nastroj>
      <nastroj id="B3">
        <znacka>Vintage</znacka>
        <druh>Modern Bass</druh>
        <barva>hnědá</barva>
        <kod-zbozi>VMB2739</kod-zbozi>
        <rok-vyroby>2011</rok-vyroby>
        <cena>7800</cena>
      </nastroj>
      <nastroj id="B4">
        <znacka>Gretsch</znacka>
        <druh>GH</druh>
        <barva>černá</barva>
        <kod-zbozi>GGH2491</kod-zbozi>
        <rok-vyroby>2017</rok-vyroby>
        <cena>6300</cena>
        <stav>skladem</stav>
      </nastroj>
  </kategorie>
<!--Kategorie 4 - Ukulele-->
  <kategorie cislo="4">
    <nazev-kat>ukulele</nazev-kat>
      <nastroj id="U1">
        <znacka>Washburn</znacka>
        <druh>sopránová</druh>
        <barva>žlutá</barva>
        <kod-zbozi>UWS3267</kod-zbozi>
        <rok-vyroby>2012</rok-vyroby>
        <cena>2200</cena>
        <stav>objednane</stav>
      </nastroj>
      <nastroj id="U2">
        <znacka>Woodi</znacka>
        <druh>koncertní</druh>
        <barva>červená</barva>
        <kod-zbozi>WKC3485</kod-zbozi>
        <rok-vyroby>2013</rok-vyroby>
        <cena>1800</cena>
        <stav>skladem</stav>
      </nastroj>
  </kategorie>
</databaze-nastroju>
</e-shop>
